using System;
using System.Diagnostics;
using System.Runtime.Serialization;

namespace MidiShapeShifter.Mss.Mapping
{
    public enum IoType { Input, Output };


    /// <summary>
    ///     A MappingEntry stores all information associated with a mapping. This information can be broken down into:
    ///     1. Information about which MSS messages will be accepted for input by the mapping (eg. InMssMsgRange)
    ///     2. Information about how to modify incomeing MSS messages. OnMssMsgRange is used to map the incoming MSS 
    ///         message's type, data1, and data2. The equation is used to map the incoming MSS message's data3.
    /// </summary>
    [DataContract]
    public class MappingEntry : IMappingEntry
    {
        public const int UNINITIALIZED_ID = -1;
        protected const MssMsgDataField DEFAULT_INPUT_TYPE = MssMsgDataField.Data3;


        /// <summary>
        /// A unique id associated with a mapping entry. The value for this is generated by the 
        /// MappingManager.
        /// </summary>
        [DataMember(Name = "Id")]
        protected int _id = UNINITIALIZED_ID;
        public int Id
        {
            get { return this._id; }
            set { this._id = value; }
        }

        /// <summary>
        ///     Specifies which MSS messages will be accepted for input as well as additional information about the 
        ///     input type
        /// </summary>
        [DataMember(Name = "InMssMsgRange")]
        protected IMssMsgRange _inMssMsgRange;
        public IMssMsgRange InMssMsgRange
        {
            get { return this._inMssMsgRange; }
            set { this._inMssMsgRange = value; }
        }

        /// <summary>
        ///     Specifies the range of messages that can be output as well as additional information about the output 
        ///     type.
        /// </summary>
        [DataMember(Name = "OutMssMsgRange")]
        protected IMssMsgRange _outMssMsgRange;
        public IMssMsgRange OutMssMsgRange
        {
            get { return this._outMssMsgRange; }
            set { this._outMssMsgRange = value; }
        }

        /// <summary>
        ///     If there are multiple mapping entries with overlapping input ranges then a single mss message can
        ///     generate several messages. This can be disabled by setting the override duplicates flag to true.
        ///     If there are two mapping entries with an overlapping inMsgRange and overrideDuplicates is set to 
        ///     true for each one, then the one closer to the top of the mapping list box overrides the other.
        /// </summary>
        [DataMember]
        public bool OverrideDuplicates { get; set; }

        /// <summary>
        ///     Contains information about the curve shape for this mapping and how it is being entered.
        /// </summary>
        [DataMember(Name = "CurveShapeInfo")]
        protected CurveShapeInfo _curveShapeInfo;
        public CurveShapeInfo CurveShapeInfo
        {
            get { return this._curveShapeInfo; }
            set { this._curveShapeInfo = value; }
        }

        [DataMember]
        public string ActiveTransformPresetName { get; set; }

        /// <summary>
        /// Specifies the primary input field. E.G. if this class was for a velocity curve then this 
        /// field would be Data3.
        /// </summary>
        [DataMember(Name = "PrimaryInputSource")]
        protected MssMsgDataField _primaryInputSource;
        public MssMsgDataField PrimaryInputSource
        {
            get { return this._primaryInputSource; }
            set { this._primaryInputSource = value; }
        }

        public MappingEntry()
        {
            this.PrimaryInputSource = DEFAULT_INPUT_TYPE;

            this.ActiveTransformPresetName = TransformPresetMgr.DEFAULT_TRANSFORM_PRESET_NAME;
        }

        public MappingEntry(MappingEntry newInstance)
        {

        }

        public void InitAllMembers(IMssMsgRange inMsgRange, IMssMsgRange outMsgRange,
                            bool overrideDuplicates, CurveShapeInfo curveShapeInfo)
        {
            this.InMssMsgRange = inMsgRange;
            this.OutMssMsgRange = outMsgRange;
            this.OverrideDuplicates = overrideDuplicates;
            this.CurveShapeInfo = curveShapeInfo;
        }

        /// <summary>
        ///     Gets a string representing an MssMsgType used by this MappingEntry
        /// </summary>
        /// <param name="ioCategory">Specifies wheather to use the type from InMssMsgRange or OutMssMsgRange</param>
        public string GetReadableMsgType(IoType ioCategory)
        {
            if (ioCategory == IoType.Input)
            {
                return MssMsg.MssMsgTypeNames[(int)this.InMssMsgRange.MsgType];
            }
            else if (ioCategory == IoType.Output)
            {
                return MssMsg.MssMsgTypeNames[(int)this.OutMssMsgRange.MsgType];
            }
            else
            {
                //Unknown IO type
                Debug.Assert(false);
                return "";
            }
        }

        /// <summary>
        ///     Gets a string representing this MappingEntry's OverrideDuplicates status
        /// </summary>
        public string GetReadableOverrideDuplicates()
        {
            return GetReadableBool(this.OverrideDuplicates);
        }

        protected string GetReadableBool(bool yesNoBool)
        {
            if (yesNoBool == true)
            {
                return "Yes";
            }
            else
            {
                return "No";
            }
        }

        object ICloneable.Clone()
        {
            return Clone();
        }

        public MappingEntry Clone()
        {
            MappingEntry mappingEntryClone = new MappingEntry();
            DeepCloneIntoExistingInstance(mappingEntryClone);
            return mappingEntryClone;
        }

        protected void DeepCloneIntoExistingInstance(MappingEntry entry)
        {
            entry.Id = this.Id;
            entry.InMssMsgRange = this.InMssMsgRange.Clone();
            entry.OutMssMsgRange = this.OutMssMsgRange.Clone();
            entry.OverrideDuplicates = this.OverrideDuplicates;
            entry.CurveShapeInfo = this.CurveShapeInfo.Clone();
            entry.PrimaryInputSource = this.PrimaryInputSource;
            entry.ActiveTransformPresetName = this.ActiveTransformPresetName;
        }

    }
}
